import type { ComplianceRule } from '../../types'

export const hipaaRules: ComplianceRule[] = [
  {
    id: 'HIPAA-164.312(a)-ACCESS',
    control: '164.312(a)',
    title: 'PHI returned without authorization validation',
    severity: 'critical',
    confidence: 'high',
    blocking: true,
    dataTypes: ['PHI'],
    requireAny: ['access', 'response'],
    missingAny: ['auth'],
    impact: 'Electronic PHI may be disclosed without verifying role, ownership, or tenant access.',
    remediation: 'Enforce resource-level authorization before reading or returning patient data.',
  },
  {
    id: 'HIPAA-164.312(b)-AUDIT',
    control: '164.312(b)',
    title: 'PHI access is not audited',
    severity: 'high',
    dataTypes: ['PHI'],
    requireAny: ['access', 'mutation'],
    missingAny: ['audit'],
    impact: 'The reviewed flow lacks an access trail for electronic PHI.',
    remediation: 'Record actor, action, patient identifier, outcome, and timestamp in an immutable audit store.',
  },
  {
    id: 'HIPAA-164.312(c)-INTEGRITY',
    control: '164.312(c)',
    title: 'PHI modification lacks integrity protection',
    severity: 'high',
    dataTypes: ['PHI'],
    requireAny: ['mutation', 'storage'],
    missingAny: ['validation', 'transaction'],
    impact: 'Patient data may be changed without validation or transactional protection.',
    remediation: 'Validate mutations and use transactional or equivalent integrity controls.',
  },
  {
    id: 'HIPAA-164.312(e)-TRANSMISSION',
    control: '164.312(e)',
    title: 'PHI transmitted over cleartext HTTP',
    severity: 'critical',
    blocking: true,
    dataTypes: ['PHI'],
    requireAll: ['http'],
    impact: 'Electronic PHI can be intercepted in transit.',
    remediation: 'Use HTTPS/TLS for every PHI-bearing request and response.',
  },
  {
    id: 'HIPAA-164.502(b)-MINIMUM',
    control: '164.502(b)',
    title: 'Response may expose more PHI than necessary',
    severity: 'high',
    dataTypes: ['PHI'],
    requireAll: ['response'],
    minFields: 4,
    impact: 'Excess fields increase breach impact and conflict with the minimum necessary rule.',
    remediation: 'Return an explicit projection containing only fields required by the caller.',
  },
  {
    id: 'HIPAA-PHI-LOG',
    control: '164.312(b)',
    title: 'PHI written to application logs',
    severity: 'critical',
    confidence: 'high',
    blocking: true,
    dataTypes: ['PHI'],
    requireAll: ['log'],
    impact: 'People and systems with log access may read protected health information.',
    remediation: 'Remove PHI from logs and retain only opaque identifiers and non-sensitive metadata.',
  },
]
