import * as vscode from 'vscode';
import { TyneValidationResult } from './validationTypes';
import { TyneCommitRecord } from './commitTypes';
import { listCommitRecords } from './commitMetadataService';
import {
  TyneWorkFeedback,
  TyneValidationStatus,
  TyneRiskLevel,
} from './automationTypes';

function mapValidationStatus(status: TyneValidationResult['status']): TyneValidationStatus {
  if (status === 'pass') { return 'pass'; }
  if (status === 'partial') { return 'partial'; }
  if (status === 'fail') { return 'fail'; }
  return 'not_run';
}

function inferRiskLevel(validation: TyneValidationResult | null): TyneRiskLevel {
  if (!validation) { return 'not_assessed'; }
  if (validation.riskLevel) { return validation.riskLevel; }
  if (validation.status === 'pass') { return 'low'; }
  if (validation.status === 'partial') { return 'medium'; }
  return 'high';
}

export function getLatestValidationForTask(
  validationResult: TyneValidationResult | null,
): { status: TyneValidationStatus; riskLevel: TyneRiskLevel } {
  if (!validationResult) {
    return { status: 'not_run', riskLevel: 'not_assessed' };
  }
  return {
    status: mapValidationStatus(validationResult.status),
    riskLevel: inferRiskLevel(validationResult),
  };
}

export function getLatestCommitForTask(
  context: vscode.ExtensionContext,
  repositoryPath: string,
  taskId: string,
): TyneCommitRecord | null {
  const commits = listCommitRecords(context, repositoryPath)
    .filter(c => c.taskId === taskId)
    .sort((a, b) => new Date(b.committedAt).getTime() - new Date(a.committedAt).getTime());
  return commits[0] ?? null;
}

export async function getCommitUrl(
  commitHash: string,
): Promise<string | null> {
  try {
    const { getGit } = await import('./gitManager');
    const git = getGit();
    if (!git) { return null; }
    const remotes = await git.getRemotes(true);
    const origin = remotes.find(r => r.name === 'origin');
    if (!origin?.refs?.fetch) { return null; }
    let url = origin.refs.fetch;
    url = url.replace(/\.git$/, '');
    if (url.startsWith('git@')) {
      url = url.replace('git@github.com:', 'https://github.com/');
    }
    return `${url}/commit/${commitHash}`;
  } catch {
    return null;
  }
}

export async function buildFeedback(
  context: vscode.ExtensionContext,
  repositoryPath: string,
  taskId: string,
  taskTitle: string | undefined,
  branchName: string | undefined,
  validationResult: TyneValidationResult | null,
  requireValidation: boolean,
): Promise<TyneWorkFeedback> {
  const { status: validationStatus, riskLevel } = getLatestValidationForTask(validationResult);
  const latestCommit = getLatestCommitForTask(context, repositoryPath, taskId);
  const commitHash = latestCommit?.shortHash ?? latestCommit?.commitHash?.slice(0, 8) ?? '';
  const commitUrl = commitHash ? await getCommitUrl(latestCommit?.commitHash ?? '') : null;
  const now = new Date();
  const synced = now.toISOString().replace('T', ' ').slice(0, 16);

  const body = formatFeedbackBody({
    taskId,
    taskTitle,
    branchName,
    commitHash,
    commitUrl: commitUrl ?? undefined,
    validationStatus,
    riskLevel,
    synced,
    requireValidation,
  });

  return {
    taskId,
    taskTitle,
    branchName,
    commitHash: commitHash || undefined,
    commitUrl: commitUrl ?? undefined,
    validationStatus,
    riskLevel,
    generatedAt: now.toISOString(),
    body,
  };
}

interface FeedbackBodyParams {
  taskId: string;
  taskTitle?: string;
  branchName?: string;
  commitHash?: string;
  commitUrl?: string;
  validationStatus: TyneValidationStatus;
  riskLevel: TyneRiskLevel;
  synced: string;
  requireValidation: boolean;
}

export function formatFeedbackBody(params: FeedbackBodyParams): string {
  const {
    taskId, taskTitle: _taskTitle, branchName, commitHash, commitUrl,
    validationStatus, riskLevel, synced, requireValidation,
  } = params;

  const commitDisplay = commitHash
    ? (commitUrl ? `[${commitHash}](${commitUrl})` : commitHash)
    : '—';

  if (validationStatus === 'not_run') {
    if (requireValidation) {
      return 'Tyne feedback blocked: validation has not been run. Run goal validation before posting feedback.';
    }
    return [
      'Work completed from Tyne.',
      '',
      'Validation: Not run',
      'Risk: Not assessed',
      branchName ? `Branch: ${branchName}` : null,
      commitHash ? `Commit: ${commitDisplay}` : null,
      `Task: ${taskId}`,
      '',
      'Generated by Tyne.',
    ].filter(l => l !== null).join('\n');
  }

  const statusLine = validationStatus === 'pass'
    ? 'Validated. Code matches goal. Risk: Low'
    : validationStatus === 'partial'
    ? 'Validation: PARTIAL\nRisk: Medium\nCode partially matches the goal.'
    : 'Validation: FAIL\nRisk: High\nCode does not fully match the goal.';

  const validationLabel = validationStatus.toUpperCase();
  const riskLabel = riskLevel === 'not_assessed' ? 'Not assessed' : riskLevel.charAt(0).toUpperCase() + riskLevel.slice(1);

  return [
    statusLine,
    '',
    `Validation: ${validationLabel}`,
    `Risk: ${riskLabel}`,
    branchName ? `Branch: ${branchName}` : null,
    commitHash ? `Commit: ${commitDisplay}` : null,
    `Task: ${taskId}`,
    `Synced: ${synced}`,
    '',
    'Generated by Tyne.',
  ].filter(l => l !== null).join('\n');
}

export async function previewFeedback(
  context: vscode.ExtensionContext,
  repositoryPath: string,
  taskId: string,
  taskTitle: string | undefined,
  branchName: string | undefined,
  validationResult: TyneValidationResult | null,
  requireValidation: boolean,
): Promise<string> {
  const feedback = await buildFeedback(
    context, repositoryPath, taskId, taskTitle, branchName, validationResult, requireValidation,
  );
  return feedback.body;
}
